"""add_buttons_to_broadcast_history

Revision ID: 0017
Revises: 0016
Create Date: 2026-04-08 17:27:16.657349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    if 'broadcast_history' in insp.get_table_names():
        has_column = False
        for col in insp.get_columns('broadcast_history'):
            if col['name'] == 'buttons':
                has_column = True
                break
        if not has_column:
            op.add_column('broadcast_history', sa.Column('buttons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcast_history', 'buttons')
    # ### end Alembic commands ###
