"""add_buttons_to_pinned_messages

Revision ID: 0018
Revises: 0017
Create Date: 2026-04-08 17:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0018'
down_revision: Union[str, None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    if 'pinned_messages' in insp.get_table_names():
        has_column = False
        for col in insp.get_columns('pinned_messages'):
            if col['name'] == 'buttons':
                has_column = True
                break
        if not has_column:
            op.add_column('pinned_messages', sa.Column('buttons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pinned_messages', 'buttons')
    # ### end Alembic commands ###
