"""add request_message_id to user_reviews

Revision ID: 1021_add_request_message_id
Revises: 1020_add_media_to_faq
Create Date: 2026-05-23 20:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1021_add_request_message_id'
down_revision: Union[str, None] = '1020_add_media_to_faq'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reviews', sa.Column('request_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_reviews', 'request_message_id')
    # ### end Alembic commands ###
