"""Add UserReview table

Revision ID: 1b0f654615fc
Revises: c4a72e00fcdf
Create Date: 2026-05-20 22:33:00.669767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b0f654615fc'
down_revision: Union[str, None] = 'c4a72e00fcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    tables = insp.get_table_names()

    if 'gifts' not in tables:
        op.create_table('gifts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('tariff_id', sa.Integer(), nullable=False),
        sa.Column('period_days', sa.Integer(), nullable=False),
        sa.Column('gifter_id', sa.Integer(), nullable=True),
        sa.Column('recipient_id', sa.Integer(), nullable=True),
        sa.Column('is_used', sa.Boolean(), nullable=False),
        sa.Column('created_at', app.database.models.AwareDateTime(), nullable=True),
        sa.Column('activated_at', app.database.models.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(['gifter_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_gifts_id'), 'gifts', ['id'], unique=False)
        op.create_index(op.f('ix_gifts_is_used'), 'gifts', ['is_used'], unique=False)
        op.create_index(op.f('ix_gifts_token'), 'gifts', ['token'], unique=True)
        
    if 'user_reviews' not in tables:
        op.create_table('user_reviews',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('review_type', sa.String(length=50), nullable=True),
        sa.Column('review_content_id', sa.String(length=255), nullable=True),
        sa.Column('star_reward_days', sa.Integer(), nullable=False),
        sa.Column('content_reward_days', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', app.database.models.AwareDateTime(), nullable=True),
        sa.Column('updated_at', app.database.models.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_reviews_id'), 'user_reviews', ['id'], unique=False)
        op.create_index(op.f('ix_user_reviews_user_id'), 'user_reviews', ['user_id'], unique=False)
        
    if 'email_templates' in tables:
        op.drop_index(op.f('ix_email_templates_notification_type'), table_name='email_templates')
        op.drop_table('email_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_templates_pkey')),
    sa.UniqueConstraint('notification_type', 'language', name=op.f('uq_email_templates_type_lang'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_email_templates_notification_type'), 'email_templates', ['notification_type'], unique=False)
    op.drop_index(op.f('ix_user_reviews_user_id'), table_name='user_reviews')
    op.drop_index(op.f('ix_user_reviews_id'), table_name='user_reviews')
    op.drop_table('user_reviews')
    op.drop_index(op.f('ix_gifts_token'), table_name='gifts')
    op.drop_index(op.f('ix_gifts_is_used'), table_name='gifts')
    op.drop_index(op.f('ix_gifts_id'), table_name='gifts')
    op.drop_table('gifts')
    # ### end Alembic commands ###
