"""Add review_text to UserReview

Revision ID: 5f8a9b1c2d3e
Revises: 1b0f654615fc
Create Date: 2026-05-21 18:47:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8a9b1c2d3e'
down_revision: Union[str, None] = '1b0f654615fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reviews', sa.Column('review_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_reviews', 'review_text')
    # ### end Alembic commands ###
